version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - REPOSITORY_URI=482825264322.dkr.ecr.ap-northeast-2.amazonaws.com/demo-repository
      - REPOSITORY_NAME=demo-repository
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 482825264322.dkr.ecr.ap-northeast-2.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t ${REPOSITORY_NAME} .
      - docker tag demo-repository:latest 482825264322.dkr.ecr.ap-northeast-2.amazonaws.com/demo-repository:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 482825264322.dkr.ecr.ap-northeast-2.amazonaws.com/demo-repository:latest
      - echo Writing image definitions file...
      - printf '[{"name":"ContainerTest","imageUri":"%s"}]' ${REPOSITORY_URI}:${IMAGE_TAG} > imagedefinitions.json
      - envsubst < taskdef.template > taskdef.json

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yaml
    - taskdef.json
